databases:
  - name: milangaWallet
    databaseName: milangaWallet
    user: milangaWallet

services:
  - type: web
    name: milangaWallet
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn milangaWallet.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4