# Generated by Django 4.1.7 on 2023-12-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('payments', models.CharField(default='0', max_length=45)),
                ('nPayments', models.CharField(default='0', max_length=45)),
                ('dueDate', models.CharField(max_length=45)),
                ('rate', models.CharField(default='0', max_length=45)),
                ('fixed', models.CharField(default='0', max_length=45)),
                ('repeat', models.CharField(default='0', max_length=45)),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('fixed', models.CharField(default='0', max_length=45)),
                ('repeat', models.CharField(default='0', max_length=45)),
            ],
            options={
                'db_table': 'ingresos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('config', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
