# Generated by Django 4.2.7 on 2023-12-05 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_ingreso_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='dueDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nPayments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='rate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='repeat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
