# Generated by Django 4.2.7 on 2023-12-05 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_delete_usuario_alter_gasto_date_alter_gasto_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 5)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='dueDate',
            field=models.DateField(default=datetime.date(2023, 12, 5)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='rate',
            field=models.FloatField(),
        ),
    ]
