# Generated by Django 4.2.7 on 2023-12-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_gasto_date_alter_gasto_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='dueDate',
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='repeat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
