# Generated by Django 4.2.7 on 2023-12-15 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_gasto_date_alter_gasto_duedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='payments',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='dueDate',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nPayments',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='repeat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='repeat',
            field=models.IntegerField(default=1),
        ),
    ]
