# Generated by Django 4.2.7 on 2023-12-16 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_gasto_payments_alter_gasto_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 16)),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='dueDate',
            field=models.DateField(default=datetime.date(2023, 12, 16)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 16)),
        ),
    ]
