# Generated by Django 4.2.7 on 2023-12-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_gasto_date_alter_gasto_duedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='fixed',
        ),
    ]
