# Generated by Django 4.2.7 on 2023-12-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_infouser_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=60),
        ),
    ]
