# Generated by Django 4.2.7 on 2023-12-17 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_infouser_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='description',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='description',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 17)),
        ),
    ]
