# Generated by Django 4.2.7 on 2023-12-18 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_gasto_description_ingreso_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 18)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 18)),
        ),
    ]
