# Generated by Django 4.2.7 on 2023-12-19 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_recordatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'forgotPassword',
            },
        ),
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=60),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
    ]
