# Generated by Django 4.2.7 on 2023-12-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_forgotpassword_alter_gasto_date_alter_infouser_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
