# Generated by Django 4.2.7 on 2023-12-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_gasto_done_ingreso_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='enviado',
            field=models.BooleanField(default=True),
        ),
    ]
