# Generated by Django 4.2.7 on 2023-12-20 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_recordatorio_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
