# Generated by Django 4.2.7 on 2023-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_gasto_numberpayment_ingreso_numberpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='numberPayment',
        ),
        migrations.AddField(
            model_name='gasto',
            name='paymentId',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
