# Generated by Django 4.2.7 on 2023-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_remove_ingreso_numberpayment_ingreso_paymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='paymentId',
            field=models.CharField(default='1_1', max_length=45),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='paymentId',
            field=models.CharField(default='1_1', max_length=45),
        ),
    ]
