# Generated by Django 4.2.7 on 2023-12-21 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_alter_gasto_paymentid_alter_ingreso_paymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 21)),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 21)),
        ),
    ]
